version: '3.5' #specify docker-compose version

services:
  angular-service: #name of the first service
    container_name: angular-container1
    build: ./ #specify directory of Dockerfile
    volumes: #volume binding
    - './:/usr/src/app'
    ports:
    - "4201:4200" #specify port forwarding
    command: >
      bash -c "npm start"
