version: '3'

services:
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 8081:8080
    build:
      context: ./
      dockerfile: Dockerfile